name: npusher
description: Flutter pusher client, laravel echo
version: 0.0.1
homepage: https://github.com/nhancv/npusher

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pusher: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

