name: npusher
description: Flutter pusher client, laravel echo
version: 1.0.6
homepage: https://github.com/nhancv/npusher

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_pusher:
    git:
      url: git://github.com/nhancv/flutter_pusher.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

